import libraries

In [119]:
import os
import json
import pandas as pd
import requests
from dotenv import load_dotenv

load api key from .env

In [120]:
load_dotenv()

True

In [121]:

api_key = os.getenv("API_KEY")

create get request for teams rankings

In [122]:
url = "https://v1.formula-1.api-sports.io/rankings/teams"

season = 2024

headers = {
  'x-apisports-key': api_key,
}
query_parameters = {'season': season }

response_teams = requests.get(url, headers=headers, params=query_parameters)


print(response_teams.status_code)

200

In [123]:
payload_teams = response_teams.json()

In [124]:
payload_teams

{'get': 'rankings',
 'parameters': {'season': '2024'},
 'errors': [],
 'results': 10,
 'response': [{'position': 1,
   'team': {'id': 2,
    'name': 'McLaren Racing',
    'logo': 'https://media.api-sports.io/formula-1/teams/2.png'},
   'points': 666,
   'season': 2024},
  {'position': 2,
   'team': {'id': 3,
    'name': 'Scuderia Ferrari',
    'logo': 'https://media.api-sports.io/formula-1/teams/3.png'},
   'points': 652,
   'season': 2024},
  {'position': 3,
   'team': {'id': 1,
    'name': 'Red Bull Racing',
    'logo': 'https://media.api-sports.io/formula-1/teams/1.png'},
   'points': 589,
   'season': 2024},
  {'position': 4,
   'team': {'id': 5,
    'name': 'Mercedes-AMG Petronas',
    'logo': 'https://media.api-sports.io/formula-1/teams/5.png'},
   'points': 468,
   'season': 2024},
  {'position': 5,
   'team': {'id': 17,
    'name': 'Aston Martin F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/17.png'},
   'points': 94,
   'season': 2024},
  {'position': 6,
   'team': {'id': 13,
    'name': 'Alpine F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
   'points': 65,
   'season': 2024},
  {'position': 7,
   'team': {'id': 14,
    'name': 'Haas F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
   'points': 58,
   'season': 2024},
  {'position': 8,
   'team': {'id': 7,
    'name': 'Racing Bulls',
    'logo': 'https://media.api-sports.io/formula-1/teams/7.png'},
   'points': 46,
   'season': 2024},
  {'position': 9,
   'team': {'id': 12,
    'name': 'Williams F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
   'points': 17,
   'season': 2024},
  {'position': 10,
   'team': {'id': 18,
    'name': 'Stake F1 Team Kick Sauber',
    'logo': 'https://media.api-sports.io/formula-1/teams/18.png'},
   'points': 4,
   'season': 2024}]}

create get request for driver rankings

In [125]:
url = "https://v1.formula-1.api-sports.io/rankings/drivers"

season = 2024

headers = {
  'x-apisports-key': api_key,
}

query_parameters = {'season': season }

response_drivers = requests.get(url, headers=headers, params=query_parameters)

print(response_drivers.status_code)

200

In [126]:
payload_drivers = response_drivers.json()

In [127]:
payload_drivers

{'get': 'rankings',
 'parameters': {'season': '2024'},
 'errors': [],
 'results': 24,
 'response': [{'position': 1,
   'driver': {'id': 25,
    'name': 'Max Verstappen',
    'abbr': 'VER',
    'number': 3,
    'image': 'https://media.api-sports.io/formula-1/drivers/25.png'},
   'team': {'id': 1,
    'name': 'Red Bull Racing',
    'logo': 'https://media.api-sports.io/formula-1/teams/1.png'},
   'points': 437,
   'wins': 9,
   'behind': None,
   'season': 2024},
  {'position': 2,
   'driver': {'id': 49,
    'name': 'Lando Norris',
    'abbr': 'NOR',
    'number': 1,
    'image': 'https://media.api-sports.io/formula-1/drivers/49.png'},
   'team': {'id': 2,
    'name': 'McLaren Racing',
    'logo': 'https://media.api-sports.io/formula-1/teams/2.png'},
   'points': 374,
   'wins': 4,
   'behind': 63,
   'season': 2024},
  {'position': 3,
   'driver': {'id': 34,
    'name': 'Charles Leclerc',
    'abbr': 'LEC',
    'number': 16,
    'image': 'https://media.api-sports.io/formula-1/drivers/34.png'},
   'team': {'id': 3,
    'name': 'Scuderia Ferrari',
    'logo': 'https://media.api-sports.io/formula-1/teams/3.png'},
   'points': 356,
   'wins': 3,
   'behind': 81,
   'season': 2024},
  {'position': 4,
   'driver': {'id': 97,
    'name': 'Oscar Piastri',
    'abbr': 'PIA',
    'number': 81,
    'image': 'https://media.api-sports.io/formula-1/drivers/97.png'},
   'team': {'id': 2,
    'name': 'McLaren Racing',
    'logo': 'https://media.api-sports.io/formula-1/teams/2.png'},
   'points': 292,
   'wins': 2,
   'behind': 145,
   'season': 2024},
  {'position': 5,
   'driver': {'id': 24,
    'name': 'Carlos Sainz Jr',
    'abbr': 'SAI',
    'number': 55,
    'image': 'https://media.api-sports.io/formula-1/drivers/24.png'},
   'team': {'id': 3,
    'name': 'Scuderia Ferrari',
    'logo': 'https://media.api-sports.io/formula-1/teams/3.png'},
   'points': 290,
   'wins': 2,
   'behind': 147,
   'season': 2024},
  {'position': 6,
   'driver': {'id': 51,
    'name': 'George Russell',
    'abbr': 'RUS',
    'number': 63,
    'image': 'https://media.api-sports.io/formula-1/drivers/51.png'},
   'team': {'id': 5,
    'name': 'Mercedes-AMG Petronas',
    'logo': 'https://media.api-sports.io/formula-1/teams/5.png'},
   'points': 245,
   'wins': 2,
   'behind': 192,
   'season': 2024},
  {'position': 7,
   'driver': {'id': 20,
    'name': 'Lewis Hamilton',
    'abbr': 'HAM',
    'number': 44,
    'image': 'https://media.api-sports.io/formula-1/drivers/20.png'},
   'team': {'id': 5,
    'name': 'Mercedes-AMG Petronas',
    'logo': 'https://media.api-sports.io/formula-1/teams/5.png'},
   'points': 223,
   'wins': 2,
   'behind': 214,
   'season': 2024},
  {'position': 8,
   'driver': {'id': 10,
    'name': 'Sergio Perez',
    'abbr': 'PER',
    'number': 11,
    'image': 'https://media.api-sports.io/formula-1/drivers/10.png'},
   'team': {'id': 1,
    'name': 'Red Bull Racing',
    'logo': 'https://media.api-sports.io/formula-1/teams/1.png'},
   'points': 152,
   'wins': 0,
   'behind': 285,
   'season': 2024},
  {'position': 9,
   'driver': {'id': 4,
    'name': 'Fernando Alonso',
    'abbr': 'ALO',
    'number': 14,
    'image': 'https://media.api-sports.io/formula-1/drivers/4.png'},
   'team': {'id': 17,
    'name': 'Aston Martin F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/17.png'},
   'points': 70,
   'wins': 0,
   'behind': 367,
   'season': 2024},
  {'position': 10,
   'driver': {'id': 36,
    'name': 'Pierre Gasly',
    'abbr': 'GAS',
    'number': 10,
    'image': 'https://media.api-sports.io/formula-1/drivers/36.png'},
   'team': {'id': 13,
    'name': 'Alpine F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
   'points': 42,
   'wins': 0,
   'behind': 395,
   'season': 2024},
  {'position': 11,
   'driver': {'id': 6,
    'name': 'Nico Hulkenberg',
    'abbr': 'HUL',
    'number': 27,
    'image': 'https://media.api-sports.io/formula-1/drivers/6.png'},
   'team': {'id': 14,
    'name': 'Haas F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
   'points': 41,
   'wins': 0,
   'behind': 396,
   'season': 2024},
  {'position': 12,
   'driver': {'id': 82,
    'name': 'Yuki Tsunoda',
    'abbr': 'TSU',
    'number': 22,
    'image': 'https://media.api-sports.io/formula-1/drivers/82.png'},
   'team': {'id': 7,
    'name': 'Racing Bulls',
    'logo': 'https://media.api-sports.io/formula-1/teams/7.png'},
   'points': 30,
   'wins': 0,
   'behind': 407,
   'season': 2024},
  {'position': 13,
   'driver': {'id': 31,
    'name': 'Lance Stroll',
    'abbr': 'STR',
    'number': 18,
    'image': 'https://media.api-sports.io/formula-1/drivers/31.png'},
   'team': {'id': 17,
    'name': 'Aston Martin F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/17.png'},
   'points': 24,
   'wins': 0,
   'behind': 413,
   'season': 2024},
  {'position': 14,
   'driver': {'id': 28,
    'name': 'Esteban Ocon',
    'abbr': 'OCO',
    'number': 31,
    'image': 'https://media.api-sports.io/formula-1/drivers/28.png'},
   'team': {'id': 13,
    'name': 'Alpine F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
   'points': 23,
   'wins': 0,
   'behind': 414,
   'season': 2024},
  {'position': 15,
   'driver': {'id': 2,
    'name': 'Kevin Magnussen',
    'abbr': 'MAG',
    'number': 20,
    'image': 'https://media.api-sports.io/formula-1/drivers/2.png'},
   'team': {'id': 14,
    'name': 'Haas F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
   'points': 16,
   'wins': 0,
   'behind': 421,
   'season': 2024},
  {'position': 16,
   'driver': {'id': 50,
    'name': 'Alexander Albon',
    'abbr': 'ALB',
    'number': 23,
    'image': 'https://media.api-sports.io/formula-1/drivers/50.png'},
   'team': {'id': 12,
    'name': 'Williams F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
   'points': 12,
   'wins': 0,
   'behind': 425,
   'season': 2024},
  {'position': 17,
   'driver': {'id': 14,
    'name': 'Daniel Ricciardo',
    'abbr': 'RIC',
    'number': 3,
    'image': 'https://media.api-sports.io/formula-1/drivers/14.png'},
   'team': {'id': 7,
    'name': 'Racing Bulls',
    'logo': 'https://media.api-sports.io/formula-1/teams/7.png'},
   'points': 12,
   'wins': 0,
   'behind': 425,
   'season': 2024},
  {'position': 18,
   'driver': {'id': 101,
    'name': 'Oliver Bearman',
    'abbr': 'BEA',
    'number': 87,
    'image': 'https://media.api-sports.io/formula-1/drivers/101.png'},
   'team': {'id': 14,
    'name': 'Haas F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
   'points': 7,
   'wins': 0,
   'behind': 430,
   'season': 2024},
  {'position': 19,
   'driver': {'id': 105,
    'name': 'Franco Colapinto',
    'abbr': None,
    'number': 43,
    'image': 'https://media.api-sports.io/formula-1/drivers/105.png'},
   'team': {'id': 12,
    'name': 'Williams F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
   'points': 5,
   'wins': 0,
   'behind': 432,
   'season': 2024},
  {'position': 20,
   'driver': {'id': 83,
    'name': 'Guanyu Zhou',
    'abbr': None,
    'number': 24,
    'image': 'https://media.api-sports.io/formula-1/drivers/83.png'},
   'team': {'id': 18,
    'name': 'Stake F1 Team Kick Sauber',
    'logo': 'https://media.api-sports.io/formula-1/teams/18.png'},
   'points': 4,
   'wins': 0,
   'behind': 433,
   'season': 2024},
  {'position': 21,
   'driver': {'id': 89,
    'name': 'Liam Lawson',
    'abbr': 'LAW',
    'number': 30,
    'image': 'https://media.api-sports.io/formula-1/drivers/89.png'},
   'team': {'id': None, 'name': None, 'logo': None},
   'points': 4,
   'wins': 0,
   'behind': 433,
   'season': 2024},
  {'position': 22,
   'driver': {'id': 5,
    'name': 'Valtteri Bottas',
    'abbr': 'BOT',
    'number': 77,
    'image': 'https://media.api-sports.io/formula-1/drivers/5.png'},
   'team': {'id': 18,
    'name': 'Stake F1 Team Kick Sauber',
    'logo': 'https://media.api-sports.io/formula-1/teams/18.png'},
   'points': None,
   'wins': 0,
   'behind': 437,
   'season': 2024},
  {'position': 23,
   'driver': {'id': 92,
    'name': 'Logan Sargeant',
    'abbr': None,
    'number': 2,
    'image': 'https://media.api-sports.io/formula-1/drivers/92.png'},
   'team': {'id': 12,
    'name': 'Williams F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
   'points': None,
   'wins': 0,
   'behind': 437,
   'season': 2024},
  {'position': 24,
   'driver': {'id': 94,
    'name': 'Jack Doohan',
    'abbr': 'DOO',
    'number': 7,
    'image': 'https://media.api-sports.io/formula-1/drivers/94.png'},
   'team': {'id': 13,
    'name': 'Alpine F1 Team',
    'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
   'points': None,
   'wins': 0,
   'behind': 437,
   'season': 2024}]}

# ====EXTRACTION====

In [128]:
print(json.dumps(payload_drivers, indent=5))

{
     "get": "rankings",
     "parameters": {
          "season": "2024"
     },
     "errors": [],
     "results": 24,
     "response": [
          {
               "position": 1,
               "driver": {
                    "id": 25,
                    "name": "Max Verstappen",
                    "abbr": "VER",
                    "number": 3,
                    "image": "https://media.api-sports.io/formula-1/drivers/25.png"
               },
               "team": {
                    "id": 1,
                    "name": "Red Bull Racing",
                    "logo": "https://media.api-sports.io/formula-1/teams/1.png"
               },
               "points": 437,
               "wins": 9,
               "behind": null,
               "season": 2024
          },
          {
               "position": 2,
               "driver": {
                    "id": 49,
                    "name": "Lando Norris",
                    "abbr": "NOR",
                    "number": 1,
                    "image": "https://media.api-sports.io/formula-1/drivers/49.png"
               },
               "team": {
                    "id": 2,
                    "name": "McLaren Racing",
                    "logo": "https://media.api-sports.io/formula-1/teams/2.png"
               },
               "points": 374,
               "wins": 4,
               "behind": 63,
               "season": 2024
          },
          {
               "position": 3,
               "driver": {
                    "id": 34,
                    "name": "Charles Leclerc",
                    "abbr": "LEC",
                    "number": 16,
                    "image": "https://media.api-sports.io/formula-1/drivers/34.png"
               },
               "team": {
                    "id": 3,
                    "name": "Scuderia Ferrari",
                    "logo": "https://media.api-sports.io/formula-1/teams/3.png"
               },
               "points": 356,
               "wins": 3,
               "behind": 81,
               "season": 2024
          },
          {
               "position": 4,
               "driver": {
                    "id": 97,
                    "name": "Oscar Piastri",
                    "abbr": "PIA",
                    "number": 81,
                    "image": "https://media.api-sports.io/formula-1/drivers/97.png"
               },
               "team": {
                    "id": 2,
                    "name": "McLaren Racing",
                    "logo": "https://media.api-sports.io/formula-1/teams/2.png"
               },
               "points": 292,
               "wins": 2,
               "behind": 145,
               "season": 2024
          },
          {
               "position": 5,
               "driver": {
                    "id": 24,
                    "name": "Carlos Sainz Jr",
                    "abbr": "SAI",
                    "number": 55,
                    "image": "https://media.api-sports.io/formula-1/drivers/24.png"
               },
               "team": {
                    "id": 3,
                    "name": "Scuderia Ferrari",
                    "logo": "https://media.api-sports.io/formula-1/teams/3.png"
               },
               "points": 290,
               "wins": 2,
               "behind": 147,
               "season": 2024
          },
          {
               "position": 6,
               "driver": {
                    "id": 51,
                    "name": "George Russell",
                    "abbr": "RUS",
                    "number": 63,
                    "image": "https://media.api-sports.io/formula-1/drivers/51.png"
               },
               "team": {
                    "id": 5,
                    "name": "Mercedes-AMG Petronas",
                    "logo": "https://media.api-sports.io/formula-1/teams/5.png"
               },
               "points": 245,
               "wins": 2,
               "behind": 192,
               "season": 2024
          },
          {
               "position": 7,
               "driver": {
                    "id": 20,
                    "name": "Lewis Hamilton",
                    "abbr": "HAM",
                    "number": 44,
                    "image": "https://media.api-sports.io/formula-1/drivers/20.png"
               },
               "team": {
                    "id": 5,
                    "name": "Mercedes-AMG Petronas",
                    "logo": "https://media.api-sports.io/formula-1/teams/5.png"
               },
               "points": 223,
               "wins": 2,
               "behind": 214,
               "season": 2024
          },
          {
               "position": 8,
               "driver": {
                    "id": 10,
                    "name": "Sergio Perez",
                    "abbr": "PER",
                    "number": 11,
                    "image": "https://media.api-sports.io/formula-1/drivers/10.png"
               },
               "team": {
                    "id": 1,
                    "name": "Red Bull Racing",
                    "logo": "https://media.api-sports.io/formula-1/teams/1.png"
               },
               "points": 152,
               "wins": 0,
               "behind": 285,
               "season": 2024
          },
          {
               "position": 9,
               "driver": {
                    "id": 4,
                    "name": "Fernando Alonso",
                    "abbr": "ALO",
                    "number": 14,
                    "image": "https://media.api-sports.io/formula-1/drivers/4.png"
               },
               "team": {
                    "id": 17,
                    "name": "Aston Martin F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/17.png"
               },
               "points": 70,
               "wins": 0,
               "behind": 367,
               "season": 2024
          },
          {
               "position": 10,
               "driver": {
                    "id": 36,
                    "name": "Pierre Gasly",
                    "abbr": "GAS",
                    "number": 10,
                    "image": "https://media.api-sports.io/formula-1/drivers/36.png"
               },
               "team": {
                    "id": 13,
                    "name": "Alpine F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/13.png"
               },
               "points": 42,
               "wins": 0,
               "behind": 395,
               "season": 2024
          },
          {
               "position": 11,
               "driver": {
                    "id": 6,
                    "name": "Nico Hulkenberg",
                    "abbr": "HUL",
                    "number": 27,
                    "image": "https://media.api-sports.io/formula-1/drivers/6.png"
               },
               "team": {
                    "id": 14,
                    "name": "Haas F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/14.png"
               },
               "points": 41,
               "wins": 0,
               "behind": 396,
               "season": 2024
          },
          {
               "position": 12,
               "driver": {
                    "id": 82,
                    "name": "Yuki Tsunoda",
                    "abbr": "TSU",
                    "number": 22,
                    "image": "https://media.api-sports.io/formula-1/drivers/82.png"
               },
               "team": {
                    "id": 7,
                    "name": "Racing Bulls",
                    "logo": "https://media.api-sports.io/formula-1/teams/7.png"
               },
               "points": 30,
               "wins": 0,
               "behind": 407,
               "season": 2024
          },
          {
               "position": 13,
               "driver": {
                    "id": 31,
                    "name": "Lance Stroll",
                    "abbr": "STR",
                    "number": 18,
                    "image": "https://media.api-sports.io/formula-1/drivers/31.png"
               },
               "team": {
                    "id": 17,
                    "name": "Aston Martin F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/17.png"
               },
               "points": 24,
               "wins": 0,
               "behind": 413,
               "season": 2024
          },
          {
               "position": 14,
               "driver": {
                    "id": 28,
                    "name": "Esteban Ocon",
                    "abbr": "OCO",
                    "number": 31,
                    "image": "https://media.api-sports.io/formula-1/drivers/28.png"
               },
               "team": {
                    "id": 13,
                    "name": "Alpine F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/13.png"
               },
               "points": 23,
               "wins": 0,
               "behind": 414,
               "season": 2024
          },
          {
               "position": 15,
               "driver": {
                    "id": 2,
                    "name": "Kevin Magnussen",
                    "abbr": "MAG",
                    "number": 20,
                    "image": "https://media.api-sports.io/formula-1/drivers/2.png"
               },
               "team": {
                    "id": 14,
                    "name": "Haas F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/14.png"
               },
               "points": 16,
               "wins": 0,
               "behind": 421,
               "season": 2024
          },
          {
               "position": 16,
               "driver": {
                    "id": 50,
                    "name": "Alexander Albon",
                    "abbr": "ALB",
                    "number": 23,
                    "image": "https://media.api-sports.io/formula-1/drivers/50.png"
               },
               "team": {
                    "id": 12,
                    "name": "Williams F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/12.png"
               },
               "points": 12,
               "wins": 0,
               "behind": 425,
               "season": 2024
          },
          {
               "position": 17,
               "driver": {
                    "id": 14,
                    "name": "Daniel Ricciardo",
                    "abbr": "RIC",
                    "number": 3,
                    "image": "https://media.api-sports.io/formula-1/drivers/14.png"
               },
               "team": {
                    "id": 7,
                    "name": "Racing Bulls",
                    "logo": "https://media.api-sports.io/formula-1/teams/7.png"
               },
               "points": 12,
               "wins": 0,
               "behind": 425,
               "season": 2024
          },
          {
               "position": 18,
               "driver": {
                    "id": 101,
                    "name": "Oliver Bearman",
                    "abbr": "BEA",
                    "number": 87,
                    "image": "https://media.api-sports.io/formula-1/drivers/101.png"
               },
               "team": {
                    "id": 14,
                    "name": "Haas F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/14.png"
               },
               "points": 7,
               "wins": 0,
               "behind": 430,
               "season": 2024
          },
          {
               "position": 19,
               "driver": {
                    "id": 105,
                    "name": "Franco Colapinto",
                    "abbr": null,
                    "number": 43,
                    "image": "https://media.api-sports.io/formula-1/drivers/105.png"
               },
               "team": {
                    "id": 12,
                    "name": "Williams F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/12.png"
               },
               "points": 5,
               "wins": 0,
               "behind": 432,
               "season": 2024
          },
          {
               "position": 20,
               "driver": {
                    "id": 83,
                    "name": "Guanyu Zhou",
                    "abbr": null,
                    "number": 24,
                    "image": "https://media.api-sports.io/formula-1/drivers/83.png"
               },
               "team": {
                    "id": 18,
                    "name": "Stake F1 Team Kick Sauber",
                    "logo": "https://media.api-sports.io/formula-1/teams/18.png"
               },
               "points": 4,
               "wins": 0,
               "behind": 433,
               "season": 2024
          },
          {
               "position": 21,
               "driver": {
                    "id": 89,
                    "name": "Liam Lawson",
                    "abbr": "LAW",
                    "number": 30,
                    "image": "https://media.api-sports.io/formula-1/drivers/89.png"
               },
               "team": {
                    "id": null,
                    "name": null,
                    "logo": null
               },
               "points": 4,
               "wins": 0,
               "behind": 433,
               "season": 2024
          },
          {
               "position": 22,
               "driver": {
                    "id": 5,
                    "name": "Valtteri Bottas",
                    "abbr": "BOT",
                    "number": 77,
                    "image": "https://media.api-sports.io/formula-1/drivers/5.png"
               },
               "team": {
                    "id": 18,
                    "name": "Stake F1 Team Kick Sauber",
                    "logo": "https://media.api-sports.io/formula-1/teams/18.png"
               },
               "points": null,
               "wins": 0,
               "behind": 437,
               "season": 2024
          },
          {
               "position": 23,
               "driver": {
                    "id": 92,
                    "name": "Logan Sargeant",
                    "abbr": null,
                    "number": 2,
                    "image": "https://media.api-sports.io/formula-1/drivers/92.png"
               },
               "team": {
                    "id": 12,
                    "name": "Williams F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/12.png"
               },
               "points": null,
               "wins": 0,
               "behind": 437,
               "season": 2024
          },
          {
               "position": 24,
               "driver": {
                    "id": 94,
                    "name": "Jack Doohan",
                    "abbr": "DOO",
                    "number": 7,
                    "image": "https://media.api-sports.io/formula-1/drivers/94.png"
               },
               "team": {
                    "id": 13,
                    "name": "Alpine F1 Team",
                    "logo": "https://media.api-sports.io/formula-1/teams/13.png"
               },
               "points": null,
               "wins": 0,
               "behind": 437,
               "season": 2024
          }
     ]
}

In [129]:
payload_teams['response'][0]['team']['logo']

'https://media.api-sports.io/formula-1/teams/2.png'

Save all images

In [130]:
import urllib.request

In [131]:

"""for t in payload_teams['response']:
    url = t['team']['logo']
    team_id = t['team']['id']
    filename = f"{team_id}.png"
    urllib.request.urlretrieve(url, filename)

print("Image saved successfully!")"""

'for t in payload_teams[\'response\']:\n    url = t[\'team\'][\'logo\']\n    team_id = t[\'team\'][\'id\']\n    filename = f"{team_id}.png"\n    urllib.request.urlretrieve(url, filename)\n\nprint("Image saved successfully!")'

In [132]:
"""for d in payload_drivers['response']:
    url = d['driver']['image']
    driver_id = d['driver']['id']
    filename = f"{driver_id}.png"
    urllib.request.urlretrieve(url, filename)

print("Image saved successfully!")"""

'for d in payload_drivers[\'response\']:\n    url = d[\'driver\'][\'image\']\n    driver_id = d[\'driver\'][\'id\']\n    filename = f"{driver_id}.png"\n    urllib.request.urlretrieve(url, filename)\n\nprint("Image saved successfully!")'

In [133]:
payload_teams['response'][0]['team']['logo']

'https://media.api-sports.io/formula-1/teams/2.png'

create paths for images

In [134]:
img_folder_drivers = r"../assets/images/drivers"
img_folder_teams = r"../assets/images/teams"

In [135]:

img_paths_drivers = [
    os.path.join(img_folder_drivers, file)
    for file in os.listdir(img_folder_drivers)
    if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))

]

img_paths_teams = [
    os.path.join(img_folder_teams, file)
    for file in os.listdir(img_folder_teams)
        if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))
]

In [136]:
import os
import re

def numeric_sort_key(path):
    filename = os.path.basename(path)
    stem = os.path.splitext(filename)[0]
    match = re.match(r"^(\d+)", stem)
    if match:
        return int(match.group(1))
    return float("inf")

img_paths_drivers = sorted(img_paths_drivers, key=numeric_sort_key)
img_paths_teams = sorted(img_paths_teams, key=numeric_sort_key)

print(img_paths_drivers)
print(img_paths_teams)

['../assets/images/drivers\\2.png', '../assets/images/drivers\\4.png', '../assets/images/drivers\\5.png', '../assets/images/drivers\\6.png', '../assets/images/drivers\\10.png', '../assets/images/drivers\\14.png', '../assets/images/drivers\\20.png', '../assets/images/drivers\\24.png', '../assets/images/drivers\\25.png', '../assets/images/drivers\\28.png', '../assets/images/drivers\\31.png', '../assets/images/drivers\\34.png', '../assets/images/drivers\\36.png', '../assets/images/drivers\\49.png', '../assets/images/drivers\\50.png', '../assets/images/drivers\\51.png', '../assets/images/drivers\\82.png', '../assets/images/drivers\\83.png', '../assets/images/drivers\\89.png', '../assets/images/drivers\\92.png', '../assets/images/drivers\\94.png', '../assets/images/drivers\\97.png', '../assets/images/drivers\\101.png', '../assets/images/drivers\\105.png']
['../assets/images/teams\\1.png', '../assets/images/teams\\2.png', '../assets/images/teams\\3.png', '../assets/images/teams\\5.png', '../assets/images/teams\\7.png', '../assets/images/teams\\12.png', '../assets/images/teams\\13.png', '../assets/images/teams\\14.png', '../assets/images/teams\\17.png', '../assets/images/teams\\18.png']

In [137]:
for t in img_paths_teams:
    print(t)

../assets/images/teams\1.png
../assets/images/teams\2.png
../assets/images/teams\3.png
../assets/images/teams\5.png
../assets/images/teams\7.png
../assets/images/teams\12.png
../assets/images/teams\13.png
../assets/images/teams\14.png
../assets/images/teams\17.png
../assets/images/teams\18.png

In [138]:
team_rows = []
team_col_names = [ 
    'team_id',
    'team_name', 
    'team_position',
    'team_points',
    'season',
    'team_logo'
]

In [139]:
payload_teams['response'][0]

{'position': 1,
 'team': {'id': 2,
  'name': 'McLaren Racing',
  'logo': 'https://media.api-sports.io/formula-1/teams/2.png'},
 'points': 666,
 'season': 2024}

In [140]:

sorted_teams = payload_teams['response'] = sorted(
    payload_teams['response'],
    key=lambda team: team['team']['id']
)

In [141]:
sorted_teams

[{'position': 3,
  'team': {'id': 1,
   'name': 'Red Bull Racing',
   'logo': 'https://media.api-sports.io/formula-1/teams/1.png'},
  'points': 589,
  'season': 2024},
 {'position': 1,
  'team': {'id': 2,
   'name': 'McLaren Racing',
   'logo': 'https://media.api-sports.io/formula-1/teams/2.png'},
  'points': 666,
  'season': 2024},
 {'position': 2,
  'team': {'id': 3,
   'name': 'Scuderia Ferrari',
   'logo': 'https://media.api-sports.io/formula-1/teams/3.png'},
  'points': 652,
  'season': 2024},
 {'position': 4,
  'team': {'id': 5,
   'name': 'Mercedes-AMG Petronas',
   'logo': 'https://media.api-sports.io/formula-1/teams/5.png'},
  'points': 468,
  'season': 2024},
 {'position': 8,
  'team': {'id': 7,
   'name': 'Racing Bulls',
   'logo': 'https://media.api-sports.io/formula-1/teams/7.png'},
  'points': 46,
  'season': 2024},
 {'position': 9,
  'team': {'id': 12,
   'name': 'Williams F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
  'points': 17,
  'season': 2024},
 {'position': 6,
  'team': {'id': 13,
   'name': 'Alpine F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
  'points': 65,
  'season': 2024},
 {'position': 7,
  'team': {'id': 14,
   'name': 'Haas F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
  'points': 58,
  'season': 2024},
 {'position': 5,
  'team': {'id': 17,
   'name': 'Aston Martin F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/17.png'},
  'points': 94,
  'season': 2024},
 {'position': 10,
  'team': {'id': 18,
   'name': 'Stake F1 Team Kick Sauber',
   'logo': 'https://media.api-sports.io/formula-1/teams/18.png'},
  'points': 4,
  'season': 2024}]

In [142]:
team_rows.clear()

In [143]:
img_index = 0

for team in sorted_teams:
    t_id = team['team']['id']
    t_name = team['team']['name']
    t_position = team['position']
    t_points = team['points']
    t_season = team['season']
    t_logo = img_paths_teams[img_index]
    img_index+=1
    team_rows.append((t_id, t_name, t_position, t_points, t_season, t_logo,))

In [144]:

for t in team_rows:
    print(t)

(1, 'Red Bull Racing', 3, 589, 2024, '../assets/images/teams\\1.png')
(2, 'McLaren Racing', 1, 666, 2024, '../assets/images/teams\\2.png')
(3, 'Scuderia Ferrari', 2, 652, 2024, '../assets/images/teams\\3.png')
(5, 'Mercedes-AMG Petronas', 4, 468, 2024, '../assets/images/teams\\5.png')
(7, 'Racing Bulls', 8, 46, 2024, '../assets/images/teams\\7.png')
(12, 'Williams F1 Team', 9, 17, 2024, '../assets/images/teams\\12.png')
(13, 'Alpine F1 Team', 6, 65, 2024, '../assets/images/teams\\13.png')
(14, 'Haas F1 Team', 7, 58, 2024, '../assets/images/teams\\14.png')
(17, 'Aston Martin F1 Team', 5, 94, 2024, '../assets/images/teams\\17.png')
(18, 'Stake F1 Team Kick Sauber', 10, 4, 2024, '../assets/images/teams\\18.png')

In [145]:
driver_rows = []
driver_col_names = [
    'driver_id',
    'driver_position',
    'driver_name',
    'abbreviation',
    'driver_wins', 
    'driver_points',
    'season',
    'driver_image',
    'team_id'
]

In [146]:
driver_rows.clear()

In [147]:
payload_drivers['response']

[{'position': 1,
  'driver': {'id': 25,
   'name': 'Max Verstappen',
   'abbr': 'VER',
   'number': 3,
   'image': 'https://media.api-sports.io/formula-1/drivers/25.png'},
  'team': {'id': 1,
   'name': 'Red Bull Racing',
   'logo': 'https://media.api-sports.io/formula-1/teams/1.png'},
  'points': 437,
  'wins': 9,
  'behind': None,
  'season': 2024},
 {'position': 2,
  'driver': {'id': 49,
   'name': 'Lando Norris',
   'abbr': 'NOR',
   'number': 1,
   'image': 'https://media.api-sports.io/formula-1/drivers/49.png'},
  'team': {'id': 2,
   'name': 'McLaren Racing',
   'logo': 'https://media.api-sports.io/formula-1/teams/2.png'},
  'points': 374,
  'wins': 4,
  'behind': 63,
  'season': 2024},
 {'position': 3,
  'driver': {'id': 34,
   'name': 'Charles Leclerc',
   'abbr': 'LEC',
   'number': 16,
   'image': 'https://media.api-sports.io/formula-1/drivers/34.png'},
  'team': {'id': 3,
   'name': 'Scuderia Ferrari',
   'logo': 'https://media.api-sports.io/formula-1/teams/3.png'},
  'points': 356,
  'wins': 3,
  'behind': 81,
  'season': 2024},
 {'position': 4,
  'driver': {'id': 97,
   'name': 'Oscar Piastri',
   'abbr': 'PIA',
   'number': 81,
   'image': 'https://media.api-sports.io/formula-1/drivers/97.png'},
  'team': {'id': 2,
   'name': 'McLaren Racing',
   'logo': 'https://media.api-sports.io/formula-1/teams/2.png'},
  'points': 292,
  'wins': 2,
  'behind': 145,
  'season': 2024},
 {'position': 5,
  'driver': {'id': 24,
   'name': 'Carlos Sainz Jr',
   'abbr': 'SAI',
   'number': 55,
   'image': 'https://media.api-sports.io/formula-1/drivers/24.png'},
  'team': {'id': 3,
   'name': 'Scuderia Ferrari',
   'logo': 'https://media.api-sports.io/formula-1/teams/3.png'},
  'points': 290,
  'wins': 2,
  'behind': 147,
  'season': 2024},
 {'position': 6,
  'driver': {'id': 51,
   'name': 'George Russell',
   'abbr': 'RUS',
   'number': 63,
   'image': 'https://media.api-sports.io/formula-1/drivers/51.png'},
  'team': {'id': 5,
   'name': 'Mercedes-AMG Petronas',
   'logo': 'https://media.api-sports.io/formula-1/teams/5.png'},
  'points': 245,
  'wins': 2,
  'behind': 192,
  'season': 2024},
 {'position': 7,
  'driver': {'id': 20,
   'name': 'Lewis Hamilton',
   'abbr': 'HAM',
   'number': 44,
   'image': 'https://media.api-sports.io/formula-1/drivers/20.png'},
  'team': {'id': 5,
   'name': 'Mercedes-AMG Petronas',
   'logo': 'https://media.api-sports.io/formula-1/teams/5.png'},
  'points': 223,
  'wins': 2,
  'behind': 214,
  'season': 2024},
 {'position': 8,
  'driver': {'id': 10,
   'name': 'Sergio Perez',
   'abbr': 'PER',
   'number': 11,
   'image': 'https://media.api-sports.io/formula-1/drivers/10.png'},
  'team': {'id': 1,
   'name': 'Red Bull Racing',
   'logo': 'https://media.api-sports.io/formula-1/teams/1.png'},
  'points': 152,
  'wins': 0,
  'behind': 285,
  'season': 2024},
 {'position': 9,
  'driver': {'id': 4,
   'name': 'Fernando Alonso',
   'abbr': 'ALO',
   'number': 14,
   'image': 'https://media.api-sports.io/formula-1/drivers/4.png'},
  'team': {'id': 17,
   'name': 'Aston Martin F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/17.png'},
  'points': 70,
  'wins': 0,
  'behind': 367,
  'season': 2024},
 {'position': 10,
  'driver': {'id': 36,
   'name': 'Pierre Gasly',
   'abbr': 'GAS',
   'number': 10,
   'image': 'https://media.api-sports.io/formula-1/drivers/36.png'},
  'team': {'id': 13,
   'name': 'Alpine F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
  'points': 42,
  'wins': 0,
  'behind': 395,
  'season': 2024},
 {'position': 11,
  'driver': {'id': 6,
   'name': 'Nico Hulkenberg',
   'abbr': 'HUL',
   'number': 27,
   'image': 'https://media.api-sports.io/formula-1/drivers/6.png'},
  'team': {'id': 14,
   'name': 'Haas F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
  'points': 41,
  'wins': 0,
  'behind': 396,
  'season': 2024},
 {'position': 12,
  'driver': {'id': 82,
   'name': 'Yuki Tsunoda',
   'abbr': 'TSU',
   'number': 22,
   'image': 'https://media.api-sports.io/formula-1/drivers/82.png'},
  'team': {'id': 7,
   'name': 'Racing Bulls',
   'logo': 'https://media.api-sports.io/formula-1/teams/7.png'},
  'points': 30,
  'wins': 0,
  'behind': 407,
  'season': 2024},
 {'position': 13,
  'driver': {'id': 31,
   'name': 'Lance Stroll',
   'abbr': 'STR',
   'number': 18,
   'image': 'https://media.api-sports.io/formula-1/drivers/31.png'},
  'team': {'id': 17,
   'name': 'Aston Martin F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/17.png'},
  'points': 24,
  'wins': 0,
  'behind': 413,
  'season': 2024},
 {'position': 14,
  'driver': {'id': 28,
   'name': 'Esteban Ocon',
   'abbr': 'OCO',
   'number': 31,
   'image': 'https://media.api-sports.io/formula-1/drivers/28.png'},
  'team': {'id': 13,
   'name': 'Alpine F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
  'points': 23,
  'wins': 0,
  'behind': 414,
  'season': 2024},
 {'position': 15,
  'driver': {'id': 2,
   'name': 'Kevin Magnussen',
   'abbr': 'MAG',
   'number': 20,
   'image': 'https://media.api-sports.io/formula-1/drivers/2.png'},
  'team': {'id': 14,
   'name': 'Haas F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
  'points': 16,
  'wins': 0,
  'behind': 421,
  'season': 2024},
 {'position': 16,
  'driver': {'id': 50,
   'name': 'Alexander Albon',
   'abbr': 'ALB',
   'number': 23,
   'image': 'https://media.api-sports.io/formula-1/drivers/50.png'},
  'team': {'id': 12,
   'name': 'Williams F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
  'points': 12,
  'wins': 0,
  'behind': 425,
  'season': 2024},
 {'position': 17,
  'driver': {'id': 14,
   'name': 'Daniel Ricciardo',
   'abbr': 'RIC',
   'number': 3,
   'image': 'https://media.api-sports.io/formula-1/drivers/14.png'},
  'team': {'id': 7,
   'name': 'Racing Bulls',
   'logo': 'https://media.api-sports.io/formula-1/teams/7.png'},
  'points': 12,
  'wins': 0,
  'behind': 425,
  'season': 2024},
 {'position': 18,
  'driver': {'id': 101,
   'name': 'Oliver Bearman',
   'abbr': 'BEA',
   'number': 87,
   'image': 'https://media.api-sports.io/formula-1/drivers/101.png'},
  'team': {'id': 14,
   'name': 'Haas F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/14.png'},
  'points': 7,
  'wins': 0,
  'behind': 430,
  'season': 2024},
 {'position': 19,
  'driver': {'id': 105,
   'name': 'Franco Colapinto',
   'abbr': None,
   'number': 43,
   'image': 'https://media.api-sports.io/formula-1/drivers/105.png'},
  'team': {'id': 12,
   'name': 'Williams F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
  'points': 5,
  'wins': 0,
  'behind': 432,
  'season': 2024},
 {'position': 20,
  'driver': {'id': 83,
   'name': 'Guanyu Zhou',
   'abbr': None,
   'number': 24,
   'image': 'https://media.api-sports.io/formula-1/drivers/83.png'},
  'team': {'id': 18,
   'name': 'Stake F1 Team Kick Sauber',
   'logo': 'https://media.api-sports.io/formula-1/teams/18.png'},
  'points': 4,
  'wins': 0,
  'behind': 433,
  'season': 2024},
 {'position': 21,
  'driver': {'id': 89,
   'name': 'Liam Lawson',
   'abbr': 'LAW',
   'number': 30,
   'image': 'https://media.api-sports.io/formula-1/drivers/89.png'},
  'team': {'id': None, 'name': None, 'logo': None},
  'points': 4,
  'wins': 0,
  'behind': 433,
  'season': 2024},
 {'position': 22,
  'driver': {'id': 5,
   'name': 'Valtteri Bottas',
   'abbr': 'BOT',
   'number': 77,
   'image': 'https://media.api-sports.io/formula-1/drivers/5.png'},
  'team': {'id': 18,
   'name': 'Stake F1 Team Kick Sauber',
   'logo': 'https://media.api-sports.io/formula-1/teams/18.png'},
  'points': None,
  'wins': 0,
  'behind': 437,
  'season': 2024},
 {'position': 23,
  'driver': {'id': 92,
   'name': 'Logan Sargeant',
   'abbr': None,
   'number': 2,
   'image': 'https://media.api-sports.io/formula-1/drivers/92.png'},
  'team': {'id': 12,
   'name': 'Williams F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/12.png'},
  'points': None,
  'wins': 0,
  'behind': 437,
  'season': 2024},
 {'position': 24,
  'driver': {'id': 94,
   'name': 'Jack Doohan',
   'abbr': 'DOO',
   'number': 7,
   'image': 'https://media.api-sports.io/formula-1/drivers/94.png'},
  'team': {'id': 13,
   'name': 'Alpine F1 Team',
   'logo': 'https://media.api-sports.io/formula-1/teams/13.png'},
  'points': None,
  'wins': 0,
  'behind': 437,
  'season': 2024}]

In [148]:
sorted_drivers = payload_drivers['response'] = sorted(
    payload_drivers['response'],
    key=lambda d: d['driver']['id']
)

In [149]:
driver_rows.clear()

img_index = 0
for d in sorted_drivers:
    d_id = d['driver']['id']
    d_position = d['position']
    d_name = d['driver']['name']
    d_abbr = d['driver']['abbr'] or "None"
    d_wins = d['wins']
    d_points = d['points'] or 0
    d_season = d['season']
    d_team_id = d['team']['id'] or 0

    d_image = img_paths_drivers[img_index]

    driver_rows.append(
        (d_id, d_position, d_name, d_abbr, d_wins, d_points, d_season, d_image, d_team_id)
    )

print(f"driver_rows count: {len(driver_rows)}")

for row in driver_rows:
    print(row)

driver_rows count: 24
(2, 15, 'Kevin Magnussen', 'MAG', 0, 16, 2024, '../assets/images/drivers\\2.png', 14)
(4, 9, 'Fernando Alonso', 'ALO', 0, 70, 2024, '../assets/images/drivers\\2.png', 17)
(5, 22, 'Valtteri Bottas', 'BOT', 0, 0, 2024, '../assets/images/drivers\\2.png', 18)
(6, 11, 'Nico Hulkenberg', 'HUL', 0, 41, 2024, '../assets/images/drivers\\2.png', 14)
(10, 8, 'Sergio Perez', 'PER', 0, 152, 2024, '../assets/images/drivers\\2.png', 1)
(14, 17, 'Daniel Ricciardo', 'RIC', 0, 12, 2024, '../assets/images/drivers\\2.png', 7)
(20, 7, 'Lewis Hamilton', 'HAM', 2, 223, 2024, '../assets/images/drivers\\2.png', 5)
(24, 5, 'Carlos Sainz Jr', 'SAI', 2, 290, 2024, '../assets/images/drivers\\2.png', 3)
(25, 1, 'Max Verstappen', 'VER', 9, 437, 2024, '../assets/images/drivers\\2.png', 1)
(28, 14, 'Esteban Ocon', 'OCO', 0, 23, 2024, '../assets/images/drivers\\2.png', 13)
(31, 13, 'Lance Stroll', 'STR', 0, 24, 2024, '../assets/images/drivers\\2.png', 17)
(34, 3, 'Charles Leclerc', 'LEC', 3, 356, 2024, '../assets/images/drivers\\2.png', 3)
(36, 10, 'Pierre Gasly', 'GAS', 0, 42, 2024, '../assets/images/drivers\\2.png', 13)
(49, 2, 'Lando Norris', 'NOR', 4, 374, 2024, '../assets/images/drivers\\2.png', 2)
(50, 16, 'Alexander Albon', 'ALB', 0, 12, 2024, '../assets/images/drivers\\2.png', 12)
(51, 6, 'George Russell', 'RUS', 2, 245, 2024, '../assets/images/drivers\\2.png', 5)
(82, 12, 'Yuki Tsunoda', 'TSU', 0, 30, 2024, '../assets/images/drivers\\2.png', 7)
(83, 20, 'Guanyu Zhou', 'None', 0, 4, 2024, '../assets/images/drivers\\2.png', 18)
(89, 21, 'Liam Lawson', 'LAW', 0, 4, 2024, '../assets/images/drivers\\2.png', 0)
(92, 23, 'Logan Sargeant', 'None', 0, 0, 2024, '../assets/images/drivers\\2.png', 12)
(94, 24, 'Jack Doohan', 'DOO', 0, 0, 2024, '../assets/images/drivers\\2.png', 13)
(97, 4, 'Oscar Piastri', 'PIA', 2, 292, 2024, '../assets/images/drivers\\2.png', 2)
(101, 18, 'Oliver Bearman', 'BEA', 0, 7, 2024, '../assets/images/drivers\\2.png', 14)
(105, 19, 'Franco Colapinto', 'None', 0, 5, 2024, '../assets/images/drivers\\2.png', 12)

# creating dataframe

In [150]:
df_teams = pd.DataFrame(team_rows, columns=team_col_names)
df_teams

,team_id,team_name,team_position,team_points,season,team_logo
0,1,Red Bull Racing,3,589,2024,../assets/images/teams\1.png
1,2,McLaren Racing,1,666,2024,../assets/images/teams\2.png
2,3,Scuderia Ferrari,2,652,2024,../assets/images/teams\3.png
3,5,Mercedes-AMG Petronas,4,468,2024,../assets/images/teams\5.png
4,7,Racing Bulls,8,46,2024,../assets/images/teams\7.png
5,12,Williams F1 Team,9,17,2024,../assets/images/teams\12.png
6,13,Alpine F1 Team,6,65,2024,../assets/images/teams\13.png
7,14,Haas F1 Team,7,58,2024,../assets/images/teams\14.png
8,17,Aston Martin F1 Team,5,94,2024,../assets/images/teams\17.png
9,18,Stake F1 Team Kick Sauber,10,4,2024,../assets/images/teams\18.png

In [151]:
df_drivers = pd.DataFrame(driver_rows, columns=driver_col_names)
# update driver's missing team id
df_drivers.loc[df_drivers["driver_id"] == 89, "team_id"] = 7
# update missing abbreviation
df_drivers.loc[df_drivers["driver_id"] == 92, "abbreviation"] = "SAR"
df_drivers.loc[df_drivers["driver_id"] == 83, "abbreviation"] = "ZHO"
df_drivers.loc[df_drivers["driver_id"] == 105, "abbreviation"] = "COL"

In [152]:
df_drivers

,driver_id,driver_position,driver_name,abbreviation,driver_wins,driver_points,season,driver_image,team_id
0,2,15,Kevin Magnussen,MAG,0,16,2024,../assets/images/drivers\2.png,14
1,4,9,Fernando Alonso,ALO,0,70,2024,../assets/images/drivers\2.png,17
2,5,22,Valtteri Bottas,BOT,0,0,2024,../assets/images/drivers\2.png,18
3,6,11,Nico Hulkenberg,HUL,0,41,2024,../assets/images/drivers\2.png,14
4,10,8,Sergio Perez,PER,0,152,2024,../assets/images/drivers\2.png,1
5,14,17,Daniel Ricciardo,RIC,0,12,2024,../assets/images/drivers\2.png,7
6,20,7,Lewis Hamilton,HAM,2,223,2024,../assets/images/drivers\2.png,5
7,24,5,Carlos Sainz Jr,SAI,2,290,2024,../assets/images/drivers\2.png,3
8,25,1,Max Verstappen,VER,9,437,2024,../assets/images/drivers\2.png,1
9,28,14,Esteban Ocon,OCO,0,23,2024,../assets/images/drivers\2.png,13
10,31,13,Lance Stroll,STR,0,24,2024,../assets/images/drivers\2.png,17
11,34,3,Charles Leclerc,LEC,3,356,2024,../assets/images/drivers\2.png,3
12,36,10,Pierre Gasly,GAS,0,42,2024,../assets/images/drivers\2.png,13
13,49,2,Lando Norris,NOR,4,374,2024,../assets/images/drivers\2.png,2
14,50,16,Alexander Albon,ALB,0,12,2024,../assets/images/drivers\2.png,12
15,51,6,George Russell,RUS,2,245,2024,../assets/images/drivers\2.png,5
16,82,12,Yuki Tsunoda,TSU,0,30,2024,../assets/images/drivers\2.png,7
17,83,20,Guanyu Zhou,ZHO,0,4,2024,../assets/images/drivers\2.png,18
18,89,21,Liam Lawson,LAW,0,4,2024,../assets/images/drivers\2.png,7
19,92,23,Logan Sargeant,SAR,0,0,2024,../assets/images/drivers\2.png,12
20,94,24,Jack Doohan,DOO,0,0,2024,../assets/images/drivers\2.png,13
21,97,4,Oscar Piastri,PIA,2,292,2024,../assets/images/drivers\2.png,2
22,101,18,Oliver Bearman,BEA,0,7,2024,../assets/images/drivers\2.png,14
23,105,19,Franco Colapinto,COL,0,5,2024,../assets/images/drivers\2.png,12

# ===LOADING===

In [153]:
load_dotenv()

True

In [154]:
sql_host        = os.getenv("HOST")
sql_port        = os.getenv("MYSQL_PORT")
sql_user        = os.getenv("MYSQL_USER")
sql_password    = os.getenv("MYSQL_PASSWORD")
sql_database    = os.getenv("MYSQL_DATABASE")

print(f"{sql_host}, {sql_port}, {sql_user}, {sql_password}, {sql_database}")

localhost, 3306, f1_user, strong_password, formula_one_db

In [155]:
from mysql import connector

In [156]:
server_connection = connector.connect(
    host=sql_host,
    port=sql_port,
    user=sql_user,
    password=sql_password,
    connection_timeout = 10,
    autocommit=False,
    raise_on_warnings=True
)

server_cursor = server_connection.cursor()
print("Connected Successfully")

server_cursor.close()
server_connection.close()

print("closed successfully")

Connected Successfully
closed successfully

connect to database

In [157]:
db_connection = connector.connect(
    host=sql_host,
        port=sql_port,
        user=sql_user,
        password=sql_password,
        database=sql_database
        
)

db_cursor = db_connection.cursor()
print("Connected successfully")

Connected successfully

start upsert operation

In [158]:
# get list of tuples from each data frame - teams and drivers
teams_tuples_list = list(df_teams.itertuples(index=False, name= None))

drivers_tuples_list = list(df_drivers.itertuples(index=False, name= None))

In [159]:
print(teams_tuples_list)
print(drivers_tuples_list)

[(1, 'Red Bull Racing', 3, 589, 2024, '../assets/images/teams\\1.png'), (2, 'McLaren Racing', 1, 666, 2024, '../assets/images/teams\\2.png'), (3, 'Scuderia Ferrari', 2, 652, 2024, '../assets/images/teams\\3.png'), (5, 'Mercedes-AMG Petronas', 4, 468, 2024, '../assets/images/teams\\5.png'), (7, 'Racing Bulls', 8, 46, 2024, '../assets/images/teams\\7.png'), (12, 'Williams F1 Team', 9, 17, 2024, '../assets/images/teams\\12.png'), (13, 'Alpine F1 Team', 6, 65, 2024, '../assets/images/teams\\13.png'), (14, 'Haas F1 Team', 7, 58, 2024, '../assets/images/teams\\14.png'), (17, 'Aston Martin F1 Team', 5, 94, 2024, '../assets/images/teams\\17.png'), (18, 'Stake F1 Team Kick Sauber', 10, 4, 2024, '../assets/images/teams\\18.png')]
[(2, 15, 'Kevin Magnussen', 'MAG', 0, 16, 2024, '../assets/images/drivers\\2.png', 14), (4, 9, 'Fernando Alonso', 'ALO', 0, 70, 2024, '../assets/images/drivers\\2.png', 17), (5, 22, 'Valtteri Bottas', 'BOT', 0, 0, 2024, '../assets/images/drivers\\2.png', 18), (6, 11, 'Nico Hulkenberg', 'HUL', 0, 41, 2024, '../assets/images/drivers\\2.png', 14), (10, 8, 'Sergio Perez', 'PER', 0, 152, 2024, '../assets/images/drivers\\2.png', 1), (14, 17, 'Daniel Ricciardo', 'RIC', 0, 12, 2024, '../assets/images/drivers\\2.png', 7), (20, 7, 'Lewis Hamilton', 'HAM', 2, 223, 2024, '../assets/images/drivers\\2.png', 5), (24, 5, 'Carlos Sainz Jr', 'SAI', 2, 290, 2024, '../assets/images/drivers\\2.png', 3), (25, 1, 'Max Verstappen', 'VER', 9, 437, 2024, '../assets/images/drivers\\2.png', 1), (28, 14, 'Esteban Ocon', 'OCO', 0, 23, 2024, '../assets/images/drivers\\2.png', 13), (31, 13, 'Lance Stroll', 'STR', 0, 24, 2024, '../assets/images/drivers\\2.png', 17), (34, 3, 'Charles Leclerc', 'LEC', 3, 356, 2024, '../assets/images/drivers\\2.png', 3), (36, 10, 'Pierre Gasly', 'GAS', 0, 42, 2024, '../assets/images/drivers\\2.png', 13), (49, 2, 'Lando Norris', 'NOR', 4, 374, 2024, '../assets/images/drivers\\2.png', 2), (50, 16, 'Alexander Albon', 'ALB', 0, 12, 2024, '../assets/images/drivers\\2.png', 12), (51, 6, 'George Russell', 'RUS', 2, 245, 2024, '../assets/images/drivers\\2.png', 5), (82, 12, 'Yuki Tsunoda', 'TSU', 0, 30, 2024, '../assets/images/drivers\\2.png', 7), (83, 20, 'Guanyu Zhou', 'ZHO', 0, 4, 2024, '../assets/images/drivers\\2.png', 18), (89, 21, 'Liam Lawson', 'LAW', 0, 4, 2024, '../assets/images/drivers\\2.png', 7), (92, 23, 'Logan Sargeant', 'SAR', 0, 0, 2024, '../assets/images/drivers\\2.png', 12), (94, 24, 'Jack Doohan', 'DOO', 0, 0, 2024, '../assets/images/drivers\\2.png', 13), (97, 4, 'Oscar Piastri', 'PIA', 2, 292, 2024, '../assets/images/drivers\\2.png', 2), (101, 18, 'Oliver Bearman', 'BEA', 0, 7, 2024, '../assets/images/drivers\\2.png', 14), (105, 19, 'Franco Colapinto', 'COL', 0, 5, 2024, '../assets/images/drivers\\2.png', 12)]

In [160]:
table_teams = "teams"
table_drivers = "drivers"

In [161]:
print(team_col_names)

['team_id', 'team_name', 'team_position', 'team_points', 'season', 'team_logo']

In [162]:
query_add_teams = f""" 

    INSERT INTO {table_teams}
    (team_id, team_name, team_position, team_points, season, team_logo)
    VALUES 
    (%s, %s, %s, %s, %s, %s) AS src
    
    ON DUPLICATE KEY UPDATE
        
    team_name = src.team_name,
    team_position = src.team_position,
    team_points = src.team_points,
    team_logo = src.team_logo

"""

In [163]:
no_rows_uploaded = len(teams_tuples_list)

In [164]:
"""try:
    db_cursor.executemany(query_add_teams, teams_tuples_list)
    db_connection.commit()
    print(f"{no_rows_uploaded} rows added")
except Exception as e:
    db_connection.rollback()
    print(e)    """

'try:\n    db_cursor.executemany(query_add_teams, teams_tuples_list)\n    db_connection.commit()\n    print(f"{no_rows_uploaded} rows added")\nexcept Exception as e:\n    db_connection.rollback()\n    print(e)    '

In [165]:
query_add_drivers = f"""

    INSERT INTO {table_drivers}
    (driver_id, driver_position, driver_name, abbreviation, driver_wins, driver_points, season, driver_image, team_id)
    VALUES
    (%s, %s, %s, %s, %s, %s, %s, %s, %s) AS src

    ON DUPLICATE KEY UPDATE

    driver_position = src.driver_position,
    driver_name = src.driver_name,
    abbreviation = src.abbreviation,
    driver_wins = src.driver_wins,
    driver_points = src.driver_points,
    season = src.season,
    driver_image = src.driver_image,
    team_id = src.team_id

"""

In [166]:
# execute many insert/upsert for drivers
"""no_rows_uploaded = len(drivers_tuples_list)

try:
    db_cursor.executemany(query_add_drivers, drivers_tuples_list)
    db_connection.commit()
    print(f"{no_rows_uploaded} driver rows added/updated")
except Exception as e:
    db_connection.rollback()
    print(f"Error inserting drivers: {e}")"""

'no_rows_uploaded = len(drivers_tuples_list)\n\ntry:\n    db_cursor.executemany(query_add_drivers, drivers_tuples_list)\n    db_connection.commit()\n    print(f"{no_rows_uploaded} driver rows added/updated")\nexcept Exception as e:\n    db_connection.rollback()\n    print(f"Error inserting drivers: {e}")'

In [167]:
db_cursor.close()
db_connection.close()

# == Saving data ==

In [168]:

"""df_teams.to_csv('teams.csv', index = 'False')
df_drivers.to_csv('drivers.csv', index = 'False')"""

"df_teams.to_csv('teams.csv', index = 'False')\ndf_drivers.to_csv('drivers.csv', index = 'False')"

# == Create Views in Mysql ==
create views in my sql
retrieve views and create a json export

In [171]:
server_connection = connector.connect(
    host=sql_host,
    port=sql_port,
    user=sql_user,
    password=sql_password,
    connection_timeout = 10,
    autocommit=False,
    raise_on_warnings=True
)

server_cursor = server_connection.cursor()
print("Connected Successfully")

Connected Successfully

In [174]:
db_connection = connector.connect(
    host=sql_host,
        port=sql_port,
        user=sql_user,
        password=sql_password,
        database=sql_database
        
)

db_cursor = db_connection.cursor()
print("Connected successfully")

Connected successfully

In [172]:
query_view_teams = "SELECT * FROM view_teams"

query_view_drivers = "SELECT * FROM view_drivers"

In [ ]:
def view_to_df(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        rows = cursor.fetchall()
        columns = [col[0] for col in cursor.description]
        return pd.DataFrame(rows, columns=columns)
    finally:
        cursor.close()

df_team_view = view_to_df(db_connection, query_view_teams)
df_driver_view = view_to_df(db_connection, query_view_drivers)

df_team_view

In [ ]:
df_team_view

In [ ]:
df_driver_view

In [181]:
df_driver_view.to_json("drivers.json", orient="records", indent=4, date_format="iso")
df_team_view.to_json("teams.json", orient="records", indent=4, date_format="iso")